project:
  title: "quarto-manuscript"
  execute-dir: project

editor: visual
filters:
  - build/pagebreak.lua
bibliography: docs/references.bib
execute: 
  freeze: auto
format:
  html:
    self-contained: true
    comments:
      hypothesis: true
  docx:
    toc: false