project:
  title: "quarto-manuscript"
  execute-dir: project

editor: visual
filters:
  - build/pagebreak.lua
bibliography: docs/references.bib
execute: 
  freeze: auto
format:
  html:
    include-after-body: build/plugins/hypothesis.html
    self-contained: true
  docx:
    toc: false